### ISSUE TITLE
Attaching a disk fails with an ssh error

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#131]
Using stemcell `light-bosh-stemcell-3232.8-softlayer-esxi-ubuntu-trusty-go_agent-public`, after creating a VM for a job with a persistent disk, the CPI successfully creates a volume but fails to mount it.

The bosh cli reports the following error:

```
  Started updating job consul_z1 > consul_z1/0 (0ba7959f-4321-4bdf-a01d-84bae8af26a6) (canary). Failed: Attaching disk '12147033' to VM '21656541': Failed to get multipath information from virtual guest `21656541`: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain (00:02:06)

Error 100: Attaching disk '12147033' to VM '21656541': Failed to get multipath information from virtual guest `21656541`: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

The task log for the deployment contains the following:

```
D, [2016-06-22 00:58:31 #22295] [canary_update(consul_z1/0 (0ba7959f-4321-4bdf-a01d-84bae8af26a6))] DEBUG -- DirectorJobRunner: External CPI sending request: {"method":"create_disk","arguments":[1024,{},"21656541"],"context":{"director_uuid":"9489a253-16f8-4dd4-b2d0-d7ac38a646b7"}} with command: /var/vcap/jobs/softlayer_cpi/bin/cpi
...
D, [2016-06-22 01:00:00 #22295] [canary_update(consul_z1/0 (0ba7959f-4321-4bdf-a01d-84bae8af26a6))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":"12147033","error":null,"log":""}, err: , exit_status: pid 23580 exit 0
...
D, [2016-06-22 01:00:00 #22295] [canary_update(consul_z1/0 (0ba7959f-4321-4bdf-a01d-84bae8af26a6))] DEBUG -- DirectorJobRunner: External CPI sending request: {"method":"attach_disk","arguments":["21656541","12147033"],"context":{"director_uuid":"9489a253-16f8-4dd4-b2d0-d7ac38a646b7"}} with command: /var/vcap/jobs/softlayer_cpi/bin/cpi
...
D, [2016-06-22 01:00:32 #22295] [canary_update(consul_z1/0 (0ba7959f-4321-4bdf-a01d-84bae8af26a6))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":{"type":"Bosh::Clouds::CloudError","message":"Attaching disk '12147033' to VM '21656541': Failed to get multipath information from virtual guest `21656541`: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain","ok_to_retry":false},"log":""}, err: , exit_status: pid 23595 exit 0
E, [2016-06-22 01:00:32 #22295] [canary_update(consul_z1/0 (0ba7959f-4321-4bdf-a01d-84bae8af26a6))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Clouds::CloudError: Attaching disk '12147033' to VM '21656541': Failed to get multipath information from virtual guest `21656541`: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain>
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3232.10.0/lib/cloud/external_cpi.rb:119:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3232.10.0/lib/cloud/external_cpi.rb:88:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3232.10.0/lib/cloud/external_cpi.rb:59:in `attach_disk'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/disk_manager.rb:271:in `create_and_attach_disk'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/disk_manager.rb:21:in `update_persistent_disk'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/instance_updater.rb:94:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/instance_updater.rb:49:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/job_updater.rb:111:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3232.10.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/job_updater.rb:109:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/event_log.rb:91:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/event_log.rb:91:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/job_updater.rb:108:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.10.0/lib/bosh/director/job_updater.rb:103:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3232.10.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3232.10.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3232.10.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3232.10.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
E, [2016-06-22 01:00:32 #22295] [] ERROR -- DirectorJobRunner: Worker thread raised exception: Attaching disk '12147033' to VM '21656541': Failed to get multipath information from virtual guest `21656541`: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3232.10.0/lib/cloud/external_cpi.rb:119:in `handle_error'
```

It appears that after the CPI grants the VM access to the disk, it tries to get multipath information from the vm:

``` go
    hasMultiPath, err := vm.hasMulitPathToolBasedOnShellScript(virtualGuest)
    if err != nil {
        return bosherr.WrapError(err, fmt.Sprintf("Failed to get multipath information from virtual guest `%d`", virtualGuest.Id))
    }
```

That, in turn, gets the root password from the VM object:

``` go
    command := fmt.Sprintf("echo `command -v multipath`")
    output, err := vm.sshClient.ExecCommand(ROOT_USER_NAME, vm.getRootPassword(virtualGuest), virtualGuest.PrimaryBackendIpAddress, command)
    if err != nil {
        return false, err
    }
```

Unfortunately, the password that's retrieved is invalid. It appears that something has changed the password for the root user between the time the VM was provisioned and the time this operation is driven.

I have manually verified that the password for the root user from the SL device page does not work with that VM but `bosh ssh` does.

Perhaps this is related to the `keep_root_password` attribute in settings.json:

``` json
{
   "agent_id" : "f4faba9a-20d7-485d-a5ee-30dd39a07ba4",
   "trusted_certs" : "",
   "env" : {
      "bosh" : {
         "keep_root_password" : false,
         "remove_dev_tools" : false,
         "password" : "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"
      },
      "persistent_disk_fs" : ""
   },
   "ntp" : [
      "0.pool.ntp.org",
      "1.pool.ntp.org"
   ],
   "networks" : {
      "cf1-dynamic" : {
         "ip" : "",
         "use_dhcp" : false,
         "netmask" : "",
         "dns" : [
            "10.0.80.11",
            "10.0.80.12"
         ],
         "type" : "dynamic",
         "preconfigured" : true,
         "mac" : "",
         "default" : null,
         "resolved" : false,
         "gateway" : ""
      },
      "cf1" : {
         "mac" : "",
         "default" : [
            "dns",
            "gateway"
         ],
         "resolved" : false,
         "gateway" : "10.155.198.1",
         "ip" : "10.155.198.9",
         "use_dhcp" : false,
         "dns" : [
            "10.0.80.11",
            "10.0.80.12"
         ],
         "netmask" : "255.255.255.192",
         "type" : "",
         "preconfigured" : true
      }
   },
   "mbus" : "nats://...",
   "blobstore" : {...}
   },
   "disks" : {
      "persistent" : null,
      "raw_ephemeral" : null,
      "ephemeral" : "/dev/xvdc",
      "system" : ""
   },
   "vm" : {
      "name" : "vm-f4faba9a-20d7-485d-a5ee-30dd39a07ba4"
   }
}
```

**Comment by jianqiu** [comment]
@sykesm 
Exactly, the problem was involved by "keep_root_password". In fact, "keep_root_password" should be true, otherwise, bosh-agent will change both `vcap`and `root` accounts` passwords according to the settings in `env` section. If `keep_root_password: true`, bosh-agent would only change the password of `vcap`, keep root password intact. So that should be valid issue to CPI, we should cover this situation in CPI.
BTW, that is a good chance I want to put forward another discussion. 
At present, in the process of  create_vm, attach_disk, detach_disk actions , CPI needed to communicate  with the provisioned vms through SSH, for instance, CPI would access the vm, and run some commands (iscsi setup, modify metadata of bosh-agent ...) which can easily result in failure, wrong root password, ssh unaccessible, etc.  
@sykesm @cppforlife
Do you have some ideas if we want to get rid of ssh between cpi and provisioned vms? Generally, we should move all these commands or os configuration to bosh-agent, but CPI needs to update agent env settings, how should CPI do that? by bosh-registry, but it is only supporting AWS, OpenStack? Thanks!

**Comment by sykesm** [comment]
For others that stumble upon this before changes are made in the CPI, if you're using the templates from https://github.com/cloudfoundry/cf-release, make sure your stub overrides the bosh environment data that's setting the password:

```yaml
meta:
  default_env:
    bosh:
      password: ~
```

That will prevent the bosh runtime from changing the password on the target VMs.

**Comment by maximilien** [comment]
We now have docs in bosh.io. Closing this issue as fixed. If there is anything missing in docs then open specifically on that. Thx
