### ISSUE TITLE
CPI panics when a manual network is the only defined network

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#166]
Using the latest version of the CPI and attempting to bring up a new bosh director with bosh init. I'm using the manifest from the networking fork that I created in the spring for our work on furnace but I'm hitting problems right away.

With the following:

```
networks:
- name: default
  type: manual
  subnets:
  - range: 10.155.248.128/28
    gateway: 10.155.248.129
    cloud_properties:
      vlan_id: *vlan_id
...

jobs:
- name: bosh
  instances: 1
  resource_pool: vms
  persistent_disk_pool: disks
  networks:
  - name: default
    static_ips: *director_ips
    default:
    - dns
    - gateway
```

Things panic with no indication of the problem, only a stack from the panic:

```
[Main] 2016/10/12 14:51:18 ERROR - Panic: runtime error: invalid memory address or nil pointer dereference
********************
goroutine 1 [running]:
runtime/debug.Stack(0xc420018050, 0xc4203fa200, 0x40)
    /Users/cfdojo/.bosh_init/installations/bbed3a38-d962-48a1-6248-ec2d36f5c124/packages/golang_1.7.1/src/runtime/debug/stack.go:24 +0x79
github.com/cloudfoundry/bosh-utils/logger.(*logger).HandlePanic(0xc4200cadc0, 0x45cdb9, 0x4)
    /Users/cfdojo/.bosh_init/installations/bbed3a38-d962-48a1-6248-ec2d36f5c124/tmp/bosh-init-release234893063/extracted_packages/bosh_softlayer_cpi/src/github.com/cloudfoundry/bosh-softlayer-cpi/Godeps/_workspace/src/github.com/cloudfoundry/bosh-utils/logger/logger.go:146 +0x102
panic(0x3edb00, 0xc420018050)
    /Users/cfdojo/.bosh_init/installations/bbed3a38-d962-48a1-6248-ec2d36f5c124/packages/golang_1.7.1/src/runtime/panic.go:458 +0x243
github.com/cloudfoundry/bosh-softlayer-cpi/action.CreateVMAction.Run(0x641b80, 0xc4200cb100, 0x641a40, 0xc420013e60, 0x63fe40, 0xc42008e2d0, 0xc420094640, 0xc420130300, 0x24, 0x14b65b, ...)
    /Users/cfdojo/.bosh_init/installations/bbed3a38-d962-48a1-6248-ec2d36f5c124/tmp/bosh-init-release234893063/extracted_packages/bosh_softlayer_cpi/src/github.com/cloudfoundry/bosh-softlayer-cpi/action/create_vm.go:71 +0x8d6
github.com/cloudfoundry/bosh-softlayer-cpi/action.(*CreateVMAction).Run(0xc420014900, 0xc420130300, 0x24, 0x14b65b, 0xc4201345e0, 0xf, 0xc4201345b0, 0xd, 0x2, 0x1000, ...)
    <autogenerated>:13 +0x130
reflect.Value.call(0x42ee40, 0xc420014900, 0x293, 0x45cccd, 0x4, 0xc4201163c0, 0x6, 0x8, 0xc420134140, 0x3e3480, ...)
    /Users/cfdojo/.bosh_init/installations/bbed3a38-d962-48a1-6248-ec2d36f5c124/packages/golang_1.7.1/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x42ee40, 0xc420014900, 0x293, 0xc4201163c0, 0x6, 0x8, 0x6, 0x8, 0x0)
    /Users/cfdojo/.bosh_init/installations/bbed3a38-d962-48a1-6248-ec2d36f5c124/packages/golang_1.7.1/src/reflect/value.go:302 +0xa4
github.com/cloudfoundry/bosh-softlayer-cpi/api/dispatcher.JSONCaller.Call(0x42ee40, 0xc420014900, 0xc420010420, 0x6, 0x6, 0xd, 0x100, 0x1cc, 0xc42012c5a0)
    /Users/cfdojo/.bosh_init/installations/bbed3a38-d962-48a1-6248-ec2d36f5c124/tmp/bosh-init-release234893063/extracted_packages/bosh_softlayer_cpi/src/github.com/cloudfoundry/bosh-softlayer-cpi/api/dispatcher/json_caller.go:43 +0x3e1
github.com/cloudfoundry/bosh-softlayer-cpi/api/dispatcher.(*JSONCaller).Call(0x6826b8, 0x42ee40, 0xc420014900, 0xc420010420, 0x6, 0x6, 0x0, 0x1cc, 0xc420121948, 0x62669)
    <autogenerated>:7 +0x81
github.com/cloudfoundry/bosh-softlayer-cpi/api/dispatcher.JSON.Dispatch(0x641a00, 0xc420013e90, 0x641ac0, 0x6826b8, 0x647f40, 0xc4200cadc0, 0xc420126600, 0x249, 0x600, 0x600, ...)
    /Users/cfdojo/.bosh_init/installations/bbed3a38-d962-48a1-6248-ec2d36f5c124/tmp/bosh-init-release234893063/extracted_packages/bosh_softlayer_cpi/src/github.com/cloudfoundry/bosh-softlayer-cpi/api/dispatcher/json.go:91 +0x5e2
github.com/cloudfoundry/bosh-softlayer-cpi/api/dispatcher.(*JSON).Dispatch(0xc420013ec0, 0xc420126600, 0x249, 0x600, 0x600, 0x0, 0x0)
    <autogenerated>:2 +0x87
github.com/cloudfoundry/bosh-softlayer-cpi/api/transport.CLI.ServeOnce(0x640dc0, 0xc42002e008, 0x640e00, 0xc42002e010, 0x641a80, 0xc420013ec0, 0x647f40, 0xc4200cadc0, 0x0, 0x0)
    /Users/cfdojo/.bosh_init/installations/bbed3a38-d962-48a1-6248-ec2d36f5c124/tmp/bosh-init-release234893063/extracted_packages/bosh_softlayer_cpi/src/github.com/cloudfoundry/bosh-softlayer-cpi/api/transport/cli.go:43 +0x26d
main.main()
    /Users/cfdojo/.bosh_init/installations/bbed3a38-d962-48a1-6248-ec2d36f5c124/tmp/bosh-init-release234893063/extracted_packages/bosh_softlayer_cpi/src/github.com/cloudfoundry/bosh-softlayer-cpi/main/main.go:45 +0x549

********************
':
              exit status 2
```

Root cause seems to be that softLayerVirtualGuestCreator.Create(...) returns a nil VM and error when it doesn't find a "dynamic" or "vip" network.

**Comment by gu-bin** [comment]
The fix is included in PR #167 

\cc @maximilien please help review and merge. Thanks.
\cc @mattcui @jianqiu

**Comment by maximilien** [comment]
Yup, looking at PR now

**Comment by maximilien** [comment]
Closing this since it seems fixed AFAIK
